name: Java CI/CD Workflow

# 触发条件：在推送到 main 或 master 分支时触发
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Step 3: 使用 Maven 构建项目
      - name: Build with Maven
        run: mvn clean install

      # Step 4: 运行 PMD 进行代码质量检查
      - name: Run PMD
        run: mvn pmd:check

      # Step 5: 上传 PMD 报告，使用 `actions/upload-artifact@v3`
      - name: Upload PMD report
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: target/site/pmd.html

  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t limingyi41/texteditor:latest .

      # Step 3: 登录 Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: 推送 Docker 镜像到 Docker Hub
      - name: Build Docker image
        run: docker build -t limingyi41/texteditor:latest ./text\ editor
