name: Java CI Workflow

# 触发条件：每当代码推送到 main 分支或发起 pull request 时触发工作流
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 JDK 17 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # 使用 Maven 构建项目
      - name: Build with Maven
        run: mvn clean install

      # 运行单元测试
      - name: Run tests
        run: mvn test

      # 运行 PMD 静态代码分析
      - name: Run PMD
        run: mvn pmd:check

      # 上传 PMD 生成的代码质量报告为构建工件
      - name: Upload PMD report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: target/site/pmd.html

  docker:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 使用 Docker 构建镜像
      - name: Build Docker image
        run: docker build -t limingyi41/texteditor3:latest .

      # 登录 Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.!Lmy200434 }}" | docker login -u "${{limingyi41}}" --password-stdin

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: docker push limingyi41/texteditor3:latest
